title: Monedario
description: Calendar-first personal finance app for iPhone, iPad, and macOS.
url: "https://yoficlemy.github.io"
baseurl: "/Monedario"
color_scheme: "light"

includes_dir: _themes/just-the-docs/_includes
layouts_dir:  _themes/just-the-docs/_layouts
sass:
  load_paths:
    - _themes/just-the-docs/_sass

just_the_docs:
  logo: "/assets/monedario-logo.png"
  favicon_ico: "/assets/favicon.ico"
  nav_external_links:
    - title: TestFlight iOS
      url: https://testflight.apple.com/join/
    - title: TestFlight macOS (Coming soon)
      url: https://testflight.apple.com/
  aux_links_new_tab: true 

# Navigation
nav_order: 1
aux_links:
  "Feature requests & votes":
    - "https://insigh.to/b/monedario"
  "GitHub":
    - "https://github.com/YofiClemy"

# Build
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# languages: ["en", "es", "fr"]